name: Build and deploy spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy sping app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
