name: Build and deploy spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy sping app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: unit Test
        run: mvn -B test --file pom.xml

      - name: build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER}}
      - name: Build Docker image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-git-actions:latest

